steps:
  # Step 1: SSH into the VM and change the working directory
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud compute ssh energy-audit-system --zone=asia-east2-c --project=randyguo-test-43165062 --command "sudo su && cd /home/randyzwguo/pdf && git pull && systemctl restart energy"

timeout: "1200s"  # Set a timeout for the build process (20 minutes)
options:
  logging: CLOUD_LOGGING_ONLY